[tool.poetry]
name = "bcbs-values"
version = "0.1.0"
description = "BCBS Values - Real Estate Valuation Platform for Benton County"
authors = ["Replit"]

[tool.poetry.dependencies]
python = ">=3.10,<4.0"
flask = "^2.3.3"
flask-sqlalchemy = "^3.1.1"
requests = "^2.31.0"
python-dotenv = "^1.0.0"
flask-migrate = "^4.0.5"
flask-dance = "^7.0.0"
werkzeug = "^2.3.7"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"