[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "bcbs_values"
version = "0.1.0"
authors = [
  { name = "BCBS Team" },
]
description = "Real estate valuation platform for Benton County"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
  "flask",
  "flask-sqlalchemy",
  "flask-login",
  "werkzeug",
  "sqlalchemy",
  "psycopg2-binary",
]

[project.urls]
"Homepage" = "https://github.com/bcbs/values"
"Bug Tracker" = "https://github.com/bcbs/values/issues"