[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "email-validator>=2.2.0",
    "fastapi>=0.115.12",
    "flask>=3.1.0",
    "flask-sqlalchemy>=3.1.1",
    "gunicorn>=23.0.0",
    "numpy>=2.2.4",
    "pandas>=2.2.3",
    "psycopg2-binary>=2.9.10",
    "python-dotenv>=1.1.0",
    "requests>=2.32.3",
    "scikit-learn>=1.6.1",
    "scipy>=1.15.2",
    "selenium>=4.30.0",
    "sqlalchemy>=2.0.40",
    "statsmodels>=0.14.4",
    "uvicorn>=0.34.0",
    "webdriver-manager>=4.0.2",
    "colorlog>=6.8.0",
    "pydantic>=2.11.1",
    "anthropic>=0.49.0",
    "werkzeug>=3.1.3",
    "pytest>=8.3.5",
    "lightgbm>=4.6.0",
    "flask-dance>=7.1.0",
]
